import { Graph } from "./graph.js";

function graph1() {
	return new Graph()
		.add({ val: 'A', x: -200, y: -15 })
		.add({ val: 'B', x: -94, y: 120 })
		.add({ val: 'C', x: 115, y: 128 })
		.add({ val: 'D', x: -73, y: -128 })
		.add({ val: 'E', x: 132, y: -94 })
		.connect({ a: 'A', b: 'B', cost: 4 })
		.connect({ a: 'A', b: 'D', cost: 2 })
		.connect({ a: 'B', b: 'C', cost: 2 })
		.connect({ a: 'B', b: 'D', cost: 3 })
		.connect({ a: 'B', b: 'E', cost: 3 })
		.connect({ a: 'D', b: 'B', cost: 1 })
		.connect({ a: 'D', b: 'C', cost: 4 })
		.connect({ a: 'D', b: 'E', cost: 5 })
		.connect({ a: 'E', b: 'C', cost: 1 })
}

function graph2() {
	return new Graph()
		.add({ val: 'O', x: -221, y: 54 })
		.add({ val: 'A', x: -101, y: 168 })
		.add({ val: 'B', x: -87, y: 5 })
		.add({ val: 'C', x: -180, y: -102 })
		.add({ val: 'D', x: 77, y: 34 })
		.add({ val: 'E', x: 51, y: -113 })
		.add({ val: 'F', x: 119, y: 181 })
		.add({ val: 'T', x: 222, y: 17 })
		.connect({ a: 'O', b: 'B', cost: 5 })
		.connect({ a: 'A', b: 'B', cost: 2 })
		.connect({ a: 'A', b: 'D', cost: 7 })
		.connect({ a: 'A', b: 'F', cost: 12 })
		.connect({ a: 'B', b: 'D', cost: 4 })
		.connect({ a: 'B', b: 'E', cost: 3 })
		.connect({ a: 'C', b: 'B', cost: 1 })
		.connect({ a: 'C', b: 'E', cost: 4 })
		.connect({ a: 'D', b: 'T', cost: 5 })
		.connect({ a: 'E', b: 'B', cost: 3 })
		.connect({ a: 'E', b: 'D', cost: 4 })
		.connect({ a: 'E', b: 'T', cost: 7 })
		.connect({ a: 'F', b: 'T', cost: 3 })
		.connect({ a: 'O', b: 'A', cost: 2 })
		.connect({ a: 'O', b: 'C', cost: 4 })
		.connect({ a: 'O', b: 'C', cost: 4 })
}

function graph3() {
	const graph = new Graph()
		.add({ val: 'A', x: 0, y: 0, })
		.add({ val: 'B', x: 90, y: 0, })
		.add({ val: 'C', x: 41, y: 79, })
		.add({ val: 'D', x: -68, y: 60, })
		.add({ val: 'E', x: -100, y: -37, })
		.add({ val: 'F', x: 5, y: -96, })
		.add({ val: 'G', x: 122, y: -79, })
		.add({ val: 'H', x: 130, y: 65, })
		.add({ val: 'I', x: -30, y: 134, })
		.add({ val: 'J', x: -156, y: 25, })
		.add({ val: 'K', x: -74, y: -130, })
		.add({ val: 'L', x: 68, y: -172, })
		.add({ val: 'M', x: 192, y: -128, })
		.add({ val: 'N', x: 194, y: -19, })
		.add({ val: 'O', x: 136, y: 150, })
		.add({ val: 'P', x: 49, y: 175, })
		.add({ val: 'Q', x: -148, y: 139, })
		.add({ val: 'R', x: -224, y: 72, })
		.add({ val: 'S', x: -204, y: -91, })
		.add({ val: 'T', x: 240, y: 64, })
		.add({ val: 'U', x: -254, y: -18, })
		.connect({ a: 'A', b: 'C' })
		.connect({ a: 'A', b: 'D' })
		.connect({ a: 'A', b: 'E' })
		.connect({ a: 'A', b: 'F' })
		.connect({ a: 'B', b: 'G' })
		.connect({ a: 'B', b: 'H' })
		.connect({ a: 'C', b: 'B' })
		.connect({ a: 'C', b: 'I' })
		.connect({ a: 'D', b: 'J' })
		.connect({ a: 'E', b: 'J' })
		.connect({ a: 'E', b: 'K' })
		.connect({ a: 'F', b: 'G' })
		.connect({ a: 'F', b: 'K' })
		.connect({ a: 'F', b: 'L' })
		.connect({ a: 'G', b: 'M' })
		.connect({ a: 'G', b: 'N' })
		.connect({ a: 'H', b: 'N' })
		.connect({ a: 'H', b: 'O' })
		.connect({ a: 'I', b: 'P' })
		.connect({ a: 'I', b: 'Q' })
		.connect({ a: 'J', b: 'Q' })
		.connect({ a: 'J', b: 'R' })
		.connect({ a: 'J', b: 'S' })
		.connect({ a: 'J', b: 'U' })
		.connect({ a: 'K', b: 'S' })
		.connect({ a: 'N', b: 'T' })
		.connect({ a: 'O', b: 'P' })

	return graph
}

export function buildGraph() {
	return graph2()
}
